server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: eureka

eureka:
  server:
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: false
